sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: linux
      node_js: 8.4.0
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar
      - snapd

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
  - npm install -g yarn

cache: yarn

install:
  - yarn

after_success:
  - yarn run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
